CREATE TABLE employees (
    employee_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    department VARCHAR(50),
    hire_date DATE DEFAULT CURRENT_DATE,
    profile_image_url VARCHAR(500),
    status VARCHAR(20) DEFAULT 'available'
);

CREATE TABLE clients (
    customer_id SERIAL PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL,
    contact_name VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    phone VARCHAR(20),
    address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sector VARCHAR(30),
    logo_url VARCHAR(500)
);

CREATE TABLE missions (
    mission_id SERIAL PRIMARY KEY,
    customer_id INT NOT NULL,
    mission_name VARCHAR(150) NOT NULL,
    description TEXT,
    start_date DATE,
    end_date DATE,
    status VARCHAR(20) DEFAULT 'In Progress',
    FOREIGN KEY (customer_id) REFERENCES clients(customer_id) ON DELETE RESTRICT
);

CREATE TABLE skills (
    skill_id SERIAL PRIMARY KEY,
    skill_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE "references" (
    reference_id SERIAL PRIMARY KEY,
    employee_id INT,
    mission_id INT NOT NULL,
    skill_id INT NOT NULL,
    role_description TEXT,
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id) ON DELETE SET NULL,
    FOREIGN KEY (mission_id) REFERENCES missions(mission_id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skills(skill_id) ON DELETE RESTRICT
);

INSERT INTO employees (first_name, last_name, email, department, hire_date, profile_image_url, status) VALUES
('Augustin', 'Morval', 'amorval@diametral.com', 'Applied AI and Data Science', '2024-01-15', 'https://media.licdn.com/dms/image/v2/D5603AQFha8Wn3UhTHQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1673342053855?e=1784160000&v=beta&t=zb5yxFR0CHBv927E98oXpGdhW3L85jJbhG1OpljuDwA', 'staffed'),
('Alexandre', 'Bidon', 'abidon@diametral.com', 'Architecture and Engineering', '2024-03-22', 'https://media.licdn.com/dms/image/v2/D4E03AQFebzOKI_dJvw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1680554817903?e=1784160000&v=beta&t=UQVh4Vud_6D6A_WEPqdu7rgtgx5jqMb1txeXE9PlY8Q', 'staffed'),
('Qifan', 'Zhang', 'qzhan@diametral.com', 'Product Delivery', '2025-05-10', 'https://media.licdn.com/dms/image/v2/D4E03AQHAiZc08t7j-w/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1678718043840?e=1784160000&v=beta&t=a0I2OE2Usx4X2OOR1ENvMXXnDw2UFWFQdulKEQb7zR4', 'staffed'),
('Samuel', 'Goutin', 'sgoutin@diametral.com', 'Architecture and Engineering', '2025-08-01', 'https://media.licdn.com/dms/image/v2/D5603AQETthag2zkIFA/profile-displayphoto-shrink_800_800/B56ZSQEfKfGoAc-/0/1737583884138?e=1784160000&v=beta&t=RCsj6dviy91AkYIsXHP6KPT0QcH9DTSK-PEhsdhx-iQ', 'available'),
('Benjamin', 'Dempouge', 'bdemouge@diametral.com', 'Applied AI and Data Science', '2026-02-14', 'https://media.licdn.com/dms/image/v2/C4E03AQFKWRHPpb0oMQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1651131831803?e=1784160000&v=beta&t=1q-SVzre1l2gVm8hgYNyBcHji5w5CCNFS8i8vPc9IZU', 'staffed'),
('Kacem', 'JORHO', 'kjorho@diametral.com', 'Applied AI and Data Science', '2026-05-26', NULL, 'available'),
('Victor', 'DE MARCILLAC', 'vdemarcillac@littlbigcode.fr', 'Applied AI and Data Science', '1970-01-01', NULL, 'available'),
('Thomas', 'DUNGLAS', 'tdunglas@diametral.com', 'Architecture and Engineering', '2020-11-02', NULL, 'available'),
('ANASS', 'LAGRAINI', 'alagraini@littlebigode.fr', 'Architecture and Engineering', '1970-10-01', NULL, 'available'),
('Robin', 'RABIER', 'rrabier@diametral.com', 'Product Delivery', '2025-03-14', NULL, 'available'),
('Amine', 'AMMENOUCHE', 'aammenouche@diametral.com', 'Architecture and Engineering', '2025-05-13', NULL, 'available'),
('Jeremy', 'GOPALAKRISNA', 'jgopalakrisna@diametral.com', 'Product Delivery', '2025-03-14', NULL, 'available'),
('Simon', 'LE BAIL', 'slebail@diametral.com', 'Product Delivery', '2025-03-14', NULL, 'available'),
('Juan', 'RODRIGUEZ', 'jfrodriguez@diametral.com', 'Product Delivery', '2025-03-14', NULL, 'available'),
('Yoan', 'EYNAUD', 'yeynaud@diametral.com', 'Product Delivery', '2024-04-01', NULL, 'available'),
('Thomas', 'GOSSIN', 'tgossin@diametral.com', 'Applied AI and Data Science', '1970-01-01', NULL, 'available'),
('Emeline', 'LESMANNE', 'elesmanne@diametral.com', 'Applied AI and Data Science', '2025-03-13', NULL, 'available'),
('Yanis', 'ALLICHE', 'yalliche@diametral.com', 'Applied AI and Data Science', '2025-05-13', NULL, 'available'),
('Siwar', 'ABBES', 'sabbes@diametral.com', 'Applied AI and Data Science', '2025-05-13', NULL, 'available'),
('Kawtar', 'CHIBANI', 'kchibani@diametral.com', 'Applied AI and Data Science', '2025-05-13', NULL, 'available'),
('Leonard', 'CHIODI', 'lchiodi@diametral.com', 'Applied AI and Data Science', '2025-05-13', NULL, 'available'),
('Stéphane', 'DONG', 'sdong@diametral.com', 'Applied AI and Data Science', '2019-10-14', NULL, 'available'),
('Meriem', 'EL MRINI', 'melmrini@diametral.com', 'Applied AI and Data Science', '2020-05-01', NULL, 'available'),
('Badr', 'KEBRIT', 'bkebrit@diametral.com', 'Applied AI and Data Science', '2025-03-02', NULL, 'available'),
('Héloïse', 'MARAND', 'hmarand@diametral.com', 'Applied AI and Data Science', '2023-11-13', NULL, 'available'),
('Alexander', 'POPPE', 'apoppe@diametral.com', 'Applied AI and Data Science', '2024-01-08', NULL, 'available'),
('Quentin', 'SABATIER', 'qsabatier@diametral.com', 'Applied AI and Data Science', '2020-03-02', NULL, 'available'),
('Arthur', 'CHANE SAM', 'achanesame@diametral.com', 'Architecture and Engineering', '2025-05-13', NULL, 'available'),
('Judy', 'AL FEHAILY', 'jalfehaily@diametral.com', 'Architecture and Engineering', '2025-05-13', NULL, 'available'),
('Rania', 'ASSAB', 'rassab@diametral.com', 'Architecture and Engineering', '2025-03-13', NULL, 'available'),
('Hany', 'AKOURY', 'hakoury@diametral.com', 'Architecture and Engineering', '2025-03-14', NULL, 'available'),
('Lea', 'NACCACHE', 'lnaccache@diametral.com', 'Applied AI and Data Science', '2025-03-14', NULL, 'available'),
('Steve', 'CHENEY', 'scheney@diametral.com', 'Architecture and Engineering', '2025-03-14', NULL, 'available'),
('Corentin', 'DRAULT', 'cdrault@diametral.com', 'Architecture and Engineering', '2025-03-14', NULL, 'available');

INSERT INTO clients (company_name, contact_name, email, phone, address, sector, logo_url) VALUES
('ACOR', 'Dr. Robert Chen', 'r.chen@apexhealth.com', '+1-555-0192', '123 Medical Plaza, Boston, MA', 'Healthcare', NULL),
('Société Générale', 'Elena Rostova', 'e.rostova@fintechglobal.com', '+1-555-4831', '77 Wall Street, New York, NY', 'Finance', 'https://logo.clearbit.com/societegenerale.com'),
('INA', 'Yasser Jequirim', 'y.jequirim@ina.fr', '+33-1-49-83-20-00', 'Bry-sur-Marne, France', 'Media', 'https://logo.clearbit.com/ina.fr'),
('ALLIANZ', 'Marcus Vance', 'm.vance@allianz.com', '+49-89-3800-0', 'Königinstraße 28, Munich, Germany', 'Energy', 'https://logo.clearbit.com/allianz.com'),
('THE BLOCKCHAIN GROUP', NULL, NULL, NULL, 'Paris, France', 'Finance', NULL),
('AXA CLIMATE', NULL, NULL, NULL, 'Paris, France', 'Finance', NULL),
('ACPR', NULL, NULL, NULL, '4 Pl. de Budapest, 75009 Paris', 'Finance', NULL),
('ONEWEALTHPLACE', NULL, NULL, NULL, 'Paris, France', 'Finance', NULL),
('GENERALI', NULL, NULL, NULL, 'Paris, France', 'Finance', NULL),
('CAGIP', NULL, NULL, NULL, '195 av Victor Hugo, 93300 Aubervilliers', 'Finance', NULL),
('BPIFRANCE', NULL, NULL, NULL, 'Paris, France', 'Finance', NULL),
('ORANO', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('SAINT GOBAIN', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('SNCF', NULL, NULL, NULL, 'Paris, France', 'Transportation', NULL),
('SANOFI', NULL, NULL, NULL, 'Paris, France', 'Healthcare', NULL),
('SERVIER', NULL, NULL, NULL, 'Paris, France', 'Healthcare', NULL),
('GIRAUDY', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('CENTER FOR HYBRID INTELLIGENCE', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('AWARE', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('L''EQUIPE', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('DELOITTE', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('GRAAL SYSTEMS', NULL, NULL, NULL, '251 Bd Pereire, 75017 Paris', 'Media', NULL),
('DATAFAB', NULL, NULL, NULL, '4 Bd des Capucines, 75009 Paris', 'Media', NULL),
('EDITIONS LEFEBVRE SARRUT', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('ALIBABA', NULL, NULL, NULL, 'Paris, France', 'Retail & Luxury', NULL),
('L’ORÉAL', NULL, NULL, NULL, 'Paris, France', 'Retail & Luxury', NULL),
('DECATHLON', NULL, NULL, NULL, 'Paris, France', 'Retail & Luxury', NULL),
('CARREFOUR', NULL, NULL, NULL, 'Paris, France', 'Retail & Luxury', NULL),
('NEARHOME', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('ONEPILOT', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('SIA', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('VEOLIA', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('ROBECO', NULL, NULL, NULL, 'Paris, France', 'Finance', NULL),
('RECHERCHE PUBLIQUE', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('ANOTHER BRAIN', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('FLATLOOKER', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('CANOPY', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('SURFMETRICS', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('GALEC', NULL, NULL, NULL, 'Paris, France', 'Retail & Luxury', NULL),
('CNRS', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('GROUP SEB', NULL, NULL, NULL, 'Paris, France', 'Retail & Luxury', NULL),
('OKUBE', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('SMART TRAFFIK', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('SAAGIE', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('BNP PARIBAS REAL ESTATE', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('WEDIAGNOSTIX', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('LAYERDEV', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('FRANCE-IOI', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('AP-HP', NULL, NULL, NULL, 'Paris, France', 'Healthcare', NULL),
('NOVAWAYS', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('EDF', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('IDEMIA', NULL, NULL, NULL, 'Paris, France', 'Aerospace & Defense', NULL),
('THALES', NULL, NULL, NULL, 'Meudon, Paris, France', 'Aerospace & Defense', NULL),
('MBDA', NULL, NULL, NULL, 'Paris, France', 'Aerospace & Defense', NULL),
('MINISTÈRE DE L''INTÉRIEUR', NULL, NULL, NULL, 'Paris, France', 'Aerospace & Defense', NULL),
('VERISURE', NULL, NULL, NULL, 'Paris, France', 'Aerospace & Defense', NULL),
('GENDARMERIE NATIONALE', NULL, NULL, NULL, 'France', 'Aerospace & Defense', NULL),
('ANSSI', NULL, NULL, NULL, 'PARIS, France', 'Aerospace & Defense', NULL),
('AUTRE', NULL, NULL, NULL, 'NA', 'Other', NULL),
('CRÉDIT AGRICOLE CIB', NULL, NULL, NULL, 'Paris, France', 'Finance', NULL),
('ANDERA PARTNERS', NULL, NULL, NULL, 'Paris, France', 'Finance', NULL),
('AXA', NULL, NULL, NULL, 'Axa Adresse, Paris, France', 'Finance', NULL),
('NATIXIS', NULL, NULL, NULL, '7 PRO GERMAINE SABLON 75013 PARIS 13', 'Finance', NULL),
('CDG CAPITAL', NULL, NULL, NULL, 'Paris, France', 'Finance', NULL),
('ASFIM', NULL, NULL, NULL, '3 Rue Laferrière, 75009 Paris', 'Finance', NULL),
('EUROCLEAR', NULL, NULL, NULL, 'Paris, France', 'Finance', NULL),
('PERNOD RICARD', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('NESTLÉ', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('SCHNEIDER ELECTRIC', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('DANONE', NULL, NULL, NULL, 'Danone, Paris, France', 'Energy', NULL),
('SAUR', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('QUALCOMM', NULL, NULL, NULL, 'PARIS, France', 'Energy', NULL),
('OKWIND', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('ENGIE', NULL, NULL, NULL, 'Paris, France', 'Energy', NULL),
('MERCEDES-BENZ', NULL, NULL, NULL, 'Paris, France', 'Transportation', NULL),
('STELLANTIS', NULL, NULL, NULL, 'Paris, France', 'Transportation', NULL),
('UBER', NULL, NULL, NULL, 'Paris, France', 'Transportation', NULL),
('DOCTOOME', NULL, NULL, NULL, 'Paris, France', 'Healthcare', NULL),
('ANS', NULL, NULL, NULL, 'Paris, France', 'Healthcare', NULL),
('INSERM', NULL, NULL, NULL, 'Paris, France', 'Healthcare', NULL),
('UNICANCER', NULL, NULL, NULL, 'Paris, France', 'Healthcare', NULL),
('CROIX ROUGE', NULL, NULL, NULL, 'Paris, France', 'Healthcare', NULL),
('GENSIGHT', NULL, NULL, NULL, 'Paris, France', 'Healthcare', NULL),
('BIOGARAN', NULL, NULL, NULL, '15 Bd Charles de Gaulle, 92700 Colombes', 'Healthcare', NULL),
('TERRITORY', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('ACCOR', NULL, NULL, NULL, '82 rue Henri Farman CS 20077 92130 Issy-les-Moulineaux France', 'Media', NULL),
('LITTLEBIGCODE', NULL, NULL, NULL, '251 Boulevard Pereire 75017 Paris', 'Media', NULL),
('AUVALIE INNOVATION', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('MAZARS', NULL, NULL, NULL, 'MAZARS, Paris, France', 'Media', NULL),
('RELEVANC', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('FRANCE TV', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('FOOTOVISION', NULL, NULL, NULL, 'Paris, FRANCE', 'Media', NULL),
('SFR', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('ALFIC', NULL, NULL, NULL, '40 Rue du Louvre, 75001', 'Media', NULL),
('BOUYGUES TELECOM', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('FREE', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('DENTSU', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('CORPORAMA', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('VIZZIT', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('CEGID', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('PÔLE EMPLOI', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('AMADEUS', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('IBM', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('VALTECH', NULL, NULL, NULL, 'Paris, France', 'Media', NULL),
('CHAUMET', NULL, NULL, NULL, 'Paris, France', 'Retail & Luxury', NULL),
('SPRING COURT', NULL, NULL, NULL, 'Paris, France', 'Retail & Luxury', NULL),
('CHANEL', NULL, NULL, NULL, 'Paris, France', 'Retail & Luxury', NULL),
('AMAZON EU', NULL, NULL, NULL, 'Amazon Adress, Paris, France', 'Retail & Luxury', NULL),
('MAC COSMETICS', NULL, NULL, NULL, 'MAC Cosmetics, Paris, France', 'Retail & Luxury', NULL),
('BNP PARIBAS', NULL, NULL, NULL, 'BNP Parisbas, Paris, France', 'Finance', NULL),
('PROJET ACADÉMIQUE', NULL, NULL, NULL, 'Paris, France', 'Media', NULL);

INSERT INTO missions (customer_id, mission_name, description, start_date, end_date, status) VALUES
(1, 'Patient Portal Upgrade', 'Migrating the legacy patient portal to a modern microservices architecture.', '2025-06-01', '2025-12-20', 'Completed'),
(2, 'Fraud Detection Model', 'Implementing an AI-driven real-time fraud detection pipeline.', '2025-09-15', '2026-04-30', 'Completed'),
(2, 'Cloud Security Audit', 'Comprehensive vulnerability assessment and AWS infrastructure hardening.', '2026-03-01', '2026-08-31', 'In Progress'),
(3, 'Support team to the data.ina.fr', 'Create tools to help and control the data of the project.', '2024-05-01', '2026-09-30', 'In Progress');

INSERT INTO skills (skill_name) VALUES
('Python'),
('SQL'),
('AWS Cloud'),
('React.js'),
('Machine Learning'),
('Penetration Testing'),
('Java');

INSERT INTO "references" (employee_id, mission_id, skill_id, role_description) VALUES
(1, 1, 4, 'Frontend Developer responsible for rebuilding the UI with React.'),
(4, 1, 7, 'Backend Engineer handles API design and Java backend microservices.'),
(2, 2, 1, 'Lead Data Scientist writing pipeline scripts in Python.'),
(2, 2, 5, 'Designed and trained the XGBoost fraud prediction models.'),
(4, 2, 2, 'Optimized SQL database indexes for high-throughput transactional logging.'),
(3, 3, 6, 'Conducted penetration testing on active network endpoints.'),
(5, 3, 3, 'Audited AWS IAM policies and configured secure VPC peering.'),
(1, 4, 4, 'Building real-time tracking components using React and WebSockets.'),
(2, 4, 2, 'Managing timescaledb databases for high-velocity sensor data streams.');
